name: Backend CD
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: 저장소 Checkout
        uses: actions/checkout@v3
        
      - name: jdk17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
        
      - name: 스프링부트 애플리케이션 install # (1)
        run: java -version
      
      - name: 스프링부트 애플리케이션 install # (1)
        run: ./gradlew clean

      - name: 스프링부트 애플리케이션 빌드 # (1)
        run: ./gradlew build

      - name: 도커 이미지 빌드 # (2)
        run: docker build -t jinu0125/kookbeetest .

      - name: Docker Hub 로그인 # (3)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Hub 퍼블리시 # (4)
        run: docker push jinu0125/kookbeetest

      - name: GCP 인스턴스 접속 및 애플리케이션 실행 # (5)
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          password: ${{ secrets.GCP_PASSWORD }}
          port: ${{ secrets.GCP_SSH_PORT }}
          script: |
            docker stop $(docker ps -a -q) 
            docker rm $(docker ps -a -q) 
            docker pull <docker_hub_username>/<image_name>
            docker run -d -p 8080:8080 --name <container_name> <docker_hub_username>/<image_name>
